### ISSUE TITLE
scoop语法介绍

### ISSUE THREAD

**Issue by ouening** [integzz/scoopet#1]
你好，请问能介绍一下scoop的语法吗，比如那个json文件里的hash，installer，persist，bin，checkver等，各个安装包地址作者是怎么找到的呢？是一个一个点击下载然后获取下载连接吗？还有hash值是自己手动计算出来的吗？

**Comment by integzz** [comment]
这个里面涉及的东西比较杂，够写一篇说明书了。我先简单说一下吧，不按顺序了。
1. 安装包的地址：这个不难，如果你想用，总能找到软件的官网，我这个库里面都是我自己用到的，所以这个不算什么问题；
2. hash：其实这个是上面那个问题涉及的关键，脚本开始构建的时候，是有点繁琐的，大概过程就是，你到官网，把软件下载下来，然后本机查看 hash，命令如下
certutil -hashfile [file] SHA256
也有 MD5 格式的，与之类似
certutil -hashfile [file] MD5
3. bin：可执行文件（如.exe）的相对路径；
4. installer：安装文件的下载链接；
5. persist：文件缓存相对路径，不是每个软件都需要；
6. checkver：这个涉及集成，如果没有集成，不写也没关系；

**Comment by kidonng** [comment]
https://github.com/lukesampson/scoop/wiki/App-Manifests
