### ISSUE TITLE
eudic@2023-11-28: hash check failed

### ISSUE THREAD

**Issue by Dagwbl** [integzz/scoopet#112]
Installing 'eudic' (2023-11-28) [64bit] from scoopet bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 149c84|OK  |    10MiB/s|C:/Users/ZJeapo/scoop/cache/eudic#2023-11-28#https_static.frdic.com_pkg_eudic_win.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of eudic_win.zip ... ERROR Hash check failed!
App:         scoopet/eudic
URL:         https://static.frdic.com/pkg/eudic_win.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    91968646ae43c19b199cb589253c68fdbfe8eb6be1f8e1b1ada78fec03da82b1
Actual:      307bf6268b49df7e8c73f63d90fa1b589d0e6349bf83461b8dc47cfc66514b0e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ivaquero/scoopet/issues/new?title=eudic%402023-11-28%3a+hash+check+failed

**Comment by ivaquero** [comment]
> Installing 'eudic' (2023-11-28) [64bit] from scoopet bucket Starting download with aria2 ... Download: Download Results: Download: gid |stat|avg speed |path/URI Download: ======+====+===========+======================================================= Download: 149c84|OK | 10MiB/s|C:/Users/ZJeapo/scoop/cache/eudic#2023-11-28#https_static.frdic.com_pkg_eudic_win.zip Download: Status Legend: Download: (OK):download completed. Checking hash of eudic_win.zip ... ERROR Hash check failed! App: scoopet/eudic URL: https://static.frdic.com/pkg/eudic_win.zip First bytes: 50 4B 03 04 14 00 00 00 Expected: 91968646ae43c19b199cb589253c68fdbfe8eb6be1f8e1b1ada78fec03da82b1 Actual: 307bf6268b49df7e8c73f63d90fa1b589d0e6349bf83461b8dc47cfc66514b0e
> 
> Please try again or create a new issue by using the following link and paste your console output: https://github.com/ivaquero/scoopet/issues/new?title=eudic%402023-11-28%3a+hash+check+failed

guess it's fixed
