### ISSUE TITLE
mathpix-snipping-tool@02.05.2: hash check failed

### ISSUE THREAD

**Issue by tkit1994** [integzz/scoopet#9]
App:         scoopet/mathpix-snipping-tool
URL:         https://mathpix.com/win_app/mathpix_snipping_tool_setup.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    0f1de0eeca1c087d472bb00254d395a1d18fe9ed47aa22b63fb07b2e750e4855
Actual:      a8ce96bdd1b828aea320a55e4c190467e773dae83e5b6b7748170379e00ce0f3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/integzz/scoopet/issues/new?title=mathpix-snipping-tool%4002.05.2%3a+hash+check+failed

**Comment by tkit1994** [comment]
why do you close this issue mannually without merging #10 to fix it？

**Comment by integzz** [comment]
Thanks for the info. In fact, I fixed it. However, in the manifest, the URL isn't based on the version and remains the same, I have to fix the hash every time and there is delay.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by integzz** [comment]
I will delete the autoupdate section to ensure the hash to be correct.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
